# Generated by Django 5.1.3 on 2024-12-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_cart_items_alter_cartitem_cart_alter_gallery_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
